#version 430 core
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (r16f, binding = 7) uniform writeonly image2D color;

uniform sampler2D gPosition;
uniform sampler2D gNormal;
uniform sampler2D texNoise;

uniform vec3 samples[64];

// parameters (you'd probably want to use them as uniforms to more easily tweak the effect)
int kernelSize = 64;
float radius = 0.5;
float bias = 0.025;

uniform float ScreenWidth;
uniform float ScreenHeight;

// tile noise texture over screen based on screen dimensions divided by noise size
vec2 noiseScale = vec2(ScreenWidth/4.0, ScreenHeight/4.0); 

uniform mat4 projection;



void main()
{


    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 UV = (vec2(gl_GlobalInvocationID.xy) + 0.5) / vec2(ScreenWidth,ScreenHeight);
    // get input for SSAO algorithm
    vec3 fragPos = texture(gPosition, UV).xyz;
    vec3 normal = normalize(texture(gNormal, UV).rgb);
    vec3 randomVec = normalize(texture(texNoise, UV * noiseScale).xyz);
    // create TBN change-of-basis matrix: from tangent-space to view-space
    vec3 tangent = normalize(randomVec - normal * dot(randomVec, normal));
    vec3 bitangent = cross(normal, tangent);
    mat3 TBN = mat3(tangent, bitangent, normal);
    // iterate over the sample kernel and calculate occlusion factor
    float occlusion = 0.0;
    for(int i = 0; i < kernelSize; ++i)
    {
        // get sample position
        vec3 samplePos = TBN * samples[i]; // from tangent to view-space
        samplePos = fragPos + samplePos * radius; 
        
        // project sample position (to sample texture) (to get position on screen/texture)
        vec4 offset = vec4(samplePos, 1.0);
        offset = projection * offset; // from view to clip-space
        offset.xyz /= offset.w; // perspective divide
        offset.xyz = offset.xyz * 0.5 + 0.5; // transform to range 0.0 - 1.0
        
        // get sample depth
        float sampleDepth = texture(gPosition, offset.xy).z; // get depth value of kernel sample
        
        // range check & accumulate
        float rangeCheck = smoothstep(0.0, 1.0, radius / abs(fragPos.z - sampleDepth));
        occlusion += (sampleDepth >= samplePos.z + bias ? 1.0 : 0.0) * rangeCheck;           
    }
    occlusion = 1.0 - (occlusion / kernelSize);
    
    imageStore(color, coords,vec4(pow(occlusion,1)));

}