#version 460 
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (rgba32f, binding = 1) uniform writeonly image2D gFinal;

layout(binding = 0) uniform sampler2D gRandom; 

uniform float time;


vec2 alias(vec2 idx, vec2 N) {
    // Shift indices above Nyquist to negative frequencies
    return mix(idx, idx - N, greaterThan(idx, N / 2));
}

vec2 cmul(vec2 a, vec2 b)
{
    vec2 r3 = a.yx;
    vec2 r1 = b.xx;
    vec2 R0 = a * r1;
    vec2 r2 = b.yy;
    vec2 R1 = r2 * r3;
    return R0 + vec2(-R1.x, R1.y);
}
  
const float G = 9.81;
const float PI = 3.14159265358979323846;

float Frequency(float k, float g, float depth)
{
	return sqrt(g * k * tanh(min(k * depth, 20)));
}


void main() {
    
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 UV = coords / vec2(512);

    float deltaK = 2 * PI / 10;
	int nx = coords.x - 512 / 2;
	int nz = coords.y - 512 / 2;
    vec2 k = vec2(nx, nz) * deltaK;
	float kLength = length(k);

    if (kLength <= 10000 && kLength >= 0.001)
	{
		float kAngle = atan(k.y, k.x);
		float omega = Frequency(kLength, -9.81, 100);
		imageStore(gFinal,coords, vec4(k.x, 1 / kLength, k.y, omega));
		//float dOmegadk = FrequencyDerivative(kLength, GravityAcceleration, Depth);

		//float spectrum = JONSWAP(omega, GravityAcceleration, Depth, Spectrums[0])
			//* DirectionSpectrum(kAngle, omega, Spectrums[0]) * ShortWavesFade(kLength, Spectrums[0]);
		//if (Spectrums[1].scale > 0)
			//spectrum += JONSWAP(omega, GravityAcceleration, Depth, Spectrums[1])
			//* DirectionSpectrum(kAngle, omega, Spectrums[1]) * ShortWavesFade(kLength, Spectrums[1]);
	//	H0K[id.xy] = float2(Noise[id.xy].x, Noise[id.xy].y)
		//	* sqrt(2 * spectrum * abs(dOmegadk) / kLength * deltaK * deltaK);
	}

    // Pick out positive and negative travelling waves.
    //vec2 a = texture(gRandom, UV).xy;
   // vec2 b = texture(gRandom, wi).xy;
   // vec2 k = uMod * alias(vec2(coords), vec2(N));
    //float k_len = length(k);

    /*
    // If this sample runs for hours on end, the cosines of very large numbers will eventually become unstable.
    // It is fairly easy to fix this by wrapping uTime,
    // and quantizing w such that wrapping uTime does not change the result.
    // See Tessendorf's paper for how to do it.
    // The sqrt(G * k_len) factor represents how fast ocean waves at different frequencies propagate.
    float w = sqrt(G * k_len) * time;
    float cw1 = cos(w);
    float sw = sin(w);
    // Complex multiply to rotate our frequency samples.

    a = cmul(a, vec2(cw1, sw));
    b = cmul(b, vec2(cw1, sw));
    b = vec2(b.x, -b.y); // Complex conjugate since we picked a frequency with the opposite direction.
    vec2 res = a + b; // Sum up forward and backwards travelling waves.
    */
    //imageStore(gFinal, coords,vec4(k,0 ,0));
}