#version 460 
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (rgba32f, binding = 1) uniform writeonly image2D gFinal;

layout(binding = 0) uniform sampler2D gRandom; 

uniform float time;

float u_gravity = 9.81;         // Acceleration due to gravity (m/s^2)
float u_windSpeed = 10.0;       // Wind speed at 10m above sea level (m/s) - Moderate breeze
float u_fetch = 10000.0;      // Fetch length (m) - 100 km, representing a limited but significant fetch
float u_depth = 100;
const float PI = 3.14159265358979323846264338327950288;


float scale = 0;
float angle = 90 / 180 * PI;
float spreadBlend;
float swell = 0.5;
float alpha = 0.076f * pow(u_gravity * u_fetch / u_windSpeed / u_windSpeed, -0.22f);
float peakOmega = 22 * pow(u_windSpeed * u_fetch / u_gravity / u_gravity, -0.33f);;
float gamma = 1;
float shortWavesFade = 1;
float _N = 512;
float _LowCutoff = 0.01;
float _HighCutoff = 10000000;



float TMACorrection(float omega) {
	float omegaH = omega * sqrt(u_depth / u_gravity);
	if (omegaH <= 1.0f)
		return 0.5f * omegaH * omegaH;
	if (omegaH < 2.0f)
		return 1.0f - 0.5f * (2.0f - omegaH) * (2.0f - omegaH);

	return 1.0f;
}

float JONSWAP(float omega) {
	float sigma = (omega <= peakOmega) ? 0.07f : 0.09f;

	float r = exp(-(omega - peakOmega) * (omega - peakOmega) / 2.0f / sigma / sigma / peakOmega / peakOmega);
	imageStore(gFinal, ivec2(gl_GlobalInvocationID.xy),vec4(-(omega - peakOmega) * (omega - peakOmega) / 2.0f / sigma / sigma / peakOmega / peakOmega,sigma,omega,peakOmega));

	float oneOverOmega = 1.0f / omega;
	float peakOmegaOverOmega = peakOmega / omega;
	return scale * TMACorrection(omega) * alpha * u_gravity * u_gravity
		* oneOverOmega * oneOverOmega * oneOverOmega * oneOverOmega * oneOverOmega
		* exp(-1.25f * peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega * peakOmegaOverOmega)
		* pow(abs(gamma), r);
}
float SpreadPower(float omega, float peakOmega) {
	if (omega > peakOmega)
		return 9.77f * pow(abs(omega / peakOmega), -2.5f);
	else
		return 6.97f * pow(abs(omega / peakOmega), 5.0f);
}
float NormalizationFactor(float s) {
    float s2 = s * s;
    float s3 = s2 * s;
    float s4 = s3 * s;
    if (s < 5) return -0.000564f * s4 + 0.00776f * s3 - 0.044f * s2 + 0.192f * s + 0.163f;
    else return -4.80e-08f * s4 + 1.07e-05f * s3 - 9.53e-04f * s2 + 5.90e-02f * s + 3.93e-01f;
}
float Cosine2s(float theta, float s) {
	return NormalizationFactor(s) * pow(abs(cos(0.5f * theta)), 2.0f * s);
}
float DirectionSpectrum(float theta, float omega) {
	float s = SpreadPower(omega, peakOmega) + 16 * tanh(min(omega / peakOmega, 20)) * swell * swell;
	return mix(2.0f / 3.1415f * cos(theta) * cos(theta), Cosine2s(theta - angle, s), spreadBlend);
}
float ShortWavesFade(float kLength) {
	return exp(-shortWavesFade * shortWavesFade * kLength * kLength);
}
float Dispersion(float kMag) {
    return sqrt(u_gravity * kMag * tanh(min(kMag * u_depth, 20)));
}
float DispersionDerivative(float kMag) {
    float th = tanh(min(kMag * u_depth, 20));
    float ch = cosh(kMag * u_depth);
    return u_gravity * (u_depth * kMag / ch / ch + th) / Dispersion(kMag) / 2.0f;
}

void main() {
    

    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    vec2 UV = id / vec2(512);

    float halfN = _N / 2.0f;

    float deltaK = 2.0f * PI / 1;
    vec2 K = (id.xy - halfN) * deltaK;
    float kLength = length(K);

 
    vec4 gauss = texture(gRandom,UV);


    if (_LowCutoff <= kLength && kLength <= _HighCutoff) {
        float kAngle = atan(K.y, K.x);
        float omega = Dispersion(kLength);

        float dOmegadk = DispersionDerivative(kLength);

        float spectrum = JONSWAP(omega) * DirectionSpectrum(kAngle, omega) * ShortWavesFade(kLength);
            
        if (scale > 0)
            spectrum += JONSWAP(omega) * DirectionSpectrum(kAngle, omega) * ShortWavesFade(kLength);
            
         //imageStore(gFinal, id, vec4(vec2(gauss.x, gauss.y) * sqrt(2 * spectrum * abs(dOmegadk) / kLength * deltaK * deltaK), 0.0f, 0.0f));
    } else {
        imageStore(gFinal, id, vec4(1,1,1,1));

    }

}