#version 460
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout (rgba32f, binding = 7) uniform writeonly image2D gFinal;

layout(binding = 0)uniform sampler2D gLighting; 
layout(binding = 2) uniform sampler2D gEmissive; 
layout(binding = 1) uniform sampler2D gSSR; 
layout(binding = 3 )uniform sampler2D gTransparent; 
layout(binding = 4 )uniform sampler2D gTransparentUV; 

uniform vec2 screen;


vec4 center;
vec4 boxBlur2D(vec2 texCoords, vec2 texOffset, int kernelSize)
{
    vec4 result = vec4(0.0);
    int kernelRadius = kernelSize / 2; // Radius of the kernel
    int sampleCount = kernelSize * kernelSize; // Total number of samples

    // Loop over the kernel in both x and y directions
    for (int x = -kernelRadius; x <= kernelRadius; ++x)
    {
        for (int y = -kernelRadius; y <= kernelRadius; ++y)
        {
            // Sample the texture at the offset position
            result += texture(gLighting, texCoords + vec2(texOffset.x * x, texOffset.y * y)) + texture(gEmissive, texCoords + vec2((texOffset.x + 0.005) * x, (texOffset.y + 0.005) * y));
        }
    }

    // Normalize by the number of samples
    result /= float(sampleCount);

    return result;
}

void main() {
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    vec2 UV = (vec2(gl_GlobalInvocationID.xy) + 0.5) / screen;

    // Retrieve data from G-buffer
    vec4 transparent = texture(gTransparent, UV).rgba;
    vec4 lighting = vec4(texture(gLighting, UV).rgb, 1.0);

    vec4 ssr = vec4(texture(gSSR, UV).rg,0,0);
    vec2 texSize  = textureSize(gSSR, 0).xy;
    vec4 emissive = vec4(texture(gEmissive, UV).rgb,1); 

    vec4 albedo = lighting + emissive;

    if(transparent.rgb != vec3(0)){
        //vec4 blurredImage = boxBlur2D(UV, vec2(0.0015), 5);

        vec4 backgroundSample = texture(gLighting, clamp(UV + transparent.xy,0.0,1.0));
        backgroundSample += texture(gEmissive, clamp(UV + transparent.xy,0.0,1.0));
        backgroundSample = boxBlur2D(UV + transparent.xy,vec2(0.0005),3);

        vec4 blended = backgroundSample + vec4(transparent.z * 2);

        imageStore(gFinal, coords, blended);
    }else{
        imageStore(gFinal, coords,vec4(albedo.xyz,1));
    }


}